### ISSUE TITLE
RBAC permission issue with user1

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/rhte_lab_2019#34]
## Issue

We have a RBAC permission issue with user1

```
oc get all,pvc,sa,imagestreams -n halkyon-fruit
NAME                      SECRETS   AGE
serviceaccount/builder    2         4h
serviceaccount/default    2         4h
serviceaccount/deployer   2         4h
Error from server (Forbidden): images.caching.internal.knative.dev is forbidden: User "user1" cannot list images.caching.internal.knative.dev in the namespace "halkyon-fruit": no RBAC policy matched
Error from server (Forbidden): clustertasks.tekton.dev is forbidden: User "user1" cannot list clustertasks.tekton.dev at the cluster scope: no RBAC policy matched
```

@jbride

**Comment by jbride** [comment]
I'd recommend appending the following to these commands that require elevated permissions:   --as=system:admin .

ie:  oc get all,pvc,sa,imagestreams -n halkyon-fruit --as=system:admin

**Comment by cmoulliard** [comment]
Sorry to miss `--as` ;-)

**Comment by ghost** [comment]
Error from server (Forbidden): clustertasks.tekton.dev is forbidden: User  cannot list clustertasks.tekton.dev at the cluster scope: no RBAC policy matched

C:\Users\laxmankumar>

C:\Users\laxmankumar>oc get pods
No resources found.

C:\Users\laxmankumar>oc get all,pvc,sa,imagestreams -n postgresql --as=system:admin
error: the server doesn't have a resource type "deploymentconfigs"

**Comment by ghost** [comment]
can anyone let me know how to resolve it

**Comment by cmoulliard** [comment]
@kumar89lax  Did you executed the command `oc get all,pvc,sa,imagestreams -n halkyon-fruit --as=system:admin` ?
